# Generated by Django 3.2.25 on 2026-05-18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.CharField(max_length=32)),
                ('level_type', models.CharField(choices=[('single', '单字'), ('multi', '多字'), ('idiom', '成语')], default='single', max_length=16)),
                ('pass_count', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('disabled', '已下架')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'levels',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=128, unique=True)),
                ('unionid', models.CharField(blank=True, default='', max_length=128)),
                ('nickname', models.CharField(blank=True, default='', max_length=128)),
                ('avatar', models.CharField(blank=True, default='', max_length=255)),
                ('coin', models.PositiveIntegerField(default=0)),
                ('energy', models.PositiveIntegerField(default=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wxcloudrun.level')),
            ],
            options={
                'db_table': 'game_users',
            },
        ),
        migrations.CreateModel(
            name='LevelAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_key', models.CharField(max_length=64)),
                ('word', models.CharField(max_length=8)),
                ('answer_type', models.CharField(choices=[('normal', '常规'), ('rare', '隐藏')], default='normal', max_length=16)),
                ('score', models.PositiveIntegerField(default=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wxcloudrun.level')),
            ],
            options={
                'db_table': 'level_answers',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('level', 'answer_key')},
            },
        ),
        migrations.CreateModel(
            name='LevelChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_key', models.CharField(max_length=16)),
                ('char_text', models.CharField(max_length=8)),
                ('full_image', models.CharField(max_length=255)),
                ('stroke_count', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chars', to='wxcloudrun.level')),
            ],
            options={
                'db_table': 'level_chars',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('level', 'char_key')},
            },
        ),
        migrations.CreateModel(
            name='LevelAnswerPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke_ids', models.JSONField(default=list)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='wxcloudrun.levelanswer')),
                ('level_char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wxcloudrun.levelchar')),
            ],
            options={
                'db_table': 'level_answer_parts',
            },
        ),
        migrations.CreateModel(
            name='LevelStroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke_key', models.CharField(max_length=16)),
                ('stroke_index', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=255)),
                ('bounds', models.JSONField(blank=True, default=dict)),
                ('level_char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strokes', to='wxcloudrun.levelchar')),
            ],
            options={
                'db_table': 'level_strokes',
                'ordering': ['stroke_index'],
                'unique_together': {('level_char', 'stroke_key')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('playing', '进行中'), ('passed', '已通关')], default='playing', max_length=16)),
                ('found_answers', models.JSONField(blank=True, default=list)),
                ('score', models.PositiveIntegerField(default=0)),
                ('first_pass_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wxcloudrun.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='wxcloudrun.gameuser')),
            ],
            options={
                'db_table': 'user_progress',
                'unique_together': {('user', 'level')},
            },
        ),
    ]
